name: Deploy to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/**'

  pull_request:
    paths:
      - 'web/**'
      - '.github/workflows/**'

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: vercel/vercel-action@v3
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
